(function(e,a){"object"===typeof module&&"object"===typeof module.exports?module.exports=e.document?a(e):function(e){if(!e.document)throw Error("TagDeliveryContent requires a window with a document");return a(e)}:a(e)})("undefined"!==typeof window?window:this,function(e){var a={GLOBAL_NAME:"TagDeliveryContent",HOST:"ad.tagdelivery.com",PROTOCOL:"https://",MAP_KEY:"_m",RETRY:1250,TIMEOUT:7E3,LOADED:!1,requestCount:0,requestMap:{},callbacks:{},isLoaded:function(){return a.LOADED},onLoadHandler:function(c){a.LOADED=
!0;a.log("Page Loaded")}};e.addEventListener?e.addEventListener("load",a.onLoadHandler):e.attachEvent("onload",a.onLoadHandler);a.log=function(){this.Log.add.apply(this.Log,[].slice.call(arguments))};a.request=function(a,d){var b=new this.Request(a,d);this.requestMap[b.id]=b;b.send();this.requestCount++;return b.id};a.Util=function(){var c={};c.head=document.head||document.getElementsByTagName("head")[0];c.generateUuid=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=
16*Math.random()|0;return("x"==a?b:b&3|8).toString(16)})};c.attachScript=function(a,b){var d=document.createElement("script");"function"==typeof b&&(d.onerror=b);d.type="text/javascript";this.head.appendChild(d);d.src=a;return d};c.getType=function(a){var b=typeof a;"object"==b&&"[object Array]"===Object.prototype.toString.call(a)&&(b="array");return b};c.isArray=function(a){return"[object Array]"==Object.prototype.toString.call(a)};c.isObject=function(a){return"[object Object]"==Object.prototype.toString.call(a)};
c.isEmptyObject=function(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0};c.arrayToQueryString=function(a){for(var b=[],d=0,c=a.length;d<c;d++){var e=a[d];"string"===typeof e?b.push(a[d].replace(/,/g,"%2C")):"number"===typeof e&&b.push(a[d])}return b.join(",")};c.objectToQueryString=function(a){var b=[],d;for(d in a)if(null!==a[d]){var c=this.getType(a[d]);c="array"==c&&0<a[d].length?this.arrayToQueryString(a[d]):"object"==c?encodeURIComponent(this.objectToQueryString(a[d])):encodeURIComponent(a[d]);
b.push(d+"="+c)}return b.join("&")};c.inArray=function(a,b){for(var d=0,c=a.length;d<c;d++)if(a[d]===b)return!0;return!1};c.getStyle=function(a){for(var b=document.styleSheets[0].rules||document.styleSheets[0].cssRules,d=0;d<b.length;d++)b[d].selectorText==a&&(b[d].cssText?alert(b[d].cssText):alert(b[d].style.cssText))};c.formatPrice=function(a,b,c){"string"!==typeof b&&(b="USD");return Number(a).toLocaleString(c,{style:"currency",currency:b})};c.shouldRender=function(a){for(var b=!1,d=0;d<a.length;d++)if(a[d].sponsored){b=
!0;break}return b};c.validateSponsoredCount=function(d){var b=0;if(a.Util.isArray(d))for(var c=0,e=d.length;c<e;c++)d[c].sponsored&&b++;else b+=d.sponsored?1:0;return b};c.decodeHtml=function(a){var b=document.createElement("textarea");b.innerHTML=a;return b.value};c.convert_to_title_case=function(a){return a.toLowerCase().replace(/^(.)|\s(.)/g,function(a){return a.toUpperCase()})};return c}();a.Log=function(){return{entries:[],toConsole:!1,add:function(){var a=[].slice.call(arguments);a.unshift(new Date);
this.entries.push(a);this.toConsole&&this.print(a)},print:function(c){c=c.slice(0);c[0]=c[0].toTimeString().substr(0,8)+"."+("000"+c[0].getMilliseconds()).substr(-3);c.unshift(a.GLOBAL_NAME);try{console.log.apply(console,c)}catch(d){}}}}();a.Pub=function(){var c={prepareDefaultResponse:function(a){return{product_id:null,request_id:a.id,sponsored:!1,impression_tracker:null,click_tracker:null,product:null}},PDP_SLOT_ID:1220,HOMEPAGE_SLOT:1210,HOST:"ad-geo.tagdelivery.com",buildUrl:function(d){return a.PROTOCOL+
c.HOST+"/request?"+a.Util.objectToQueryString(d.parameters)},modifyRequest:function(a){a.parameters.targets.category.includes("redes")&&a.parameters.targets.category.push("cables");a.parameters.targets.category.includes("tablets---ebooks")&&a.parameters.targets.category.push("tablets","tabletpc");a.parameters.targets.category.includes("audio---foto---video")&&a.parameters.targets.category.push("audio-foto-video");a.parameters.targets.category.includes("consolas---gaming")&&a.parameters.targets.category.push("consolas-gaming");
a.parameters.targets.category.includes("tablets-ebooks")&&a.parameters.targets.category.push("tablets","tabletpc");a.parameters.targets.category.includes("portatiles-2-en-1-convertibles")&&a.parameters.targets.category.push("portatiles");if([this.PDP_SLOT_ID,this.HOMEPAGE_SLOT].includes(a.parameters.slot))return a.active=!1,a},modifyResponse:function(d,b){if(e.location.host.includes("www.pccomponentes.pt")){if(a.Util.isArray(b)){for(var c=[],h=0;h<b.length;h++){var f=b[h];null!=f.product&&(f.product.priceCurrent=
parseFloat(f.product.portugalPrice),f.product.priceList=parseFloat(f.product.portugalPrice));c.push(f)}return c}null!==b.product&&(b.product.priceCurrent=parseFloat(b.product.portugalPrice),b.product.priceList=parseFloat(b.product.portugalPrice))}return b}};return c}();a.Request=function(){return function(c,d){this.id=a.Util.generateUuid();this.inputs=null;this.parameters={targets:null,slot:null,deferred:null,batch:null,pos:null,format:null,width:null,height:null,callback:null,passthru:null,template:null,
count:null,count_fill:null,attributes:null};this.callback=d;this.timeoutRef={};this.retryAfter=a.RETRY;this.timeLeft=a.TIMEOUT;this.numTries=0;this.locked=!1;this.active=!0;this.map=!1;this.baseUrl=a.PROTOCOL+a.HOST+"/request?";this.url=null;this.requestedAt=+new Date;this.renderedAt=this.returnedAt=this.receivedAt=this.sentAt=null;a.log("received request",this.id,this.inputs);this.applyInputs=function(a){if("object"==typeof a){this.inputs=Object.assign({},a);for(var b in a)this.parameters.hasOwnProperty(b)&&
(this.parameters[b]=a[b])}else this.inputs=a};this.applyInputs(c);this.modifyForPub=function(){if("function"==typeof a.Pub.modifyRequest){var b=a.Pub.modifyRequest(this);if("object"==typeof b)for(var c in b)"inputs"!==c&&(this[c]=b[c])}};this.getCallbackKey=function(){return"_"+this.id.replace(/-/g,"_")};this.registerCallback=function(){var b=this.getCallbackKey();null===this.parameters.callback&&(this.parameters.callback=[a.GLOBAL_NAME,"callbacks",b].join("."));var c=this.id;a.callbacks[b]=function(b){a.requestMap[c].processResponse(b)}};
this.setRetryTime=function(b){this.timeLeft=b||a.TIMEOUT;this.retryAfter=Math.min(this.timeLeft||this.retryAfter,a.RETRY)};this.setRetry=function(){var b=this;this.timeoutRef=setTimeout(function(){0>=b.timeLeft?b.cancel():a.isLoaded()?(a.log("resending after",b.id,+new Date-b.requestedAt),b.numTries++,b.cancel()):(a.log("Pseudo timeout during loading",b.id,b.url),b.setRetry())},b.retryAfter||a.RETRY);a.isLoaded()&&(this.retryAfter=Math.min(this.retryAfter,this.timeLeft),this.timeLeft-=this.retryAfter)};
this.noRetry=function(){clearTimeout(this.timeoutRef)};this.setUrl=function(){"function"==typeof a.Pub.buildUrl?this.url=a.Pub.buildUrl(this):this.map&&!this.inputs.hasOwnProperty(a.MAP_KEY)?this.url="function"==typeof a.Pub.getMapRequest?a.Pub.getMapRequest(this):"https://tools.tagdelivery.com/requests/map?request="+encodeURIComponent(JSON.stringify({id:this.id,parameters:this.parameters})):this.url=this.baseUrl+a.Util.objectToQueryString(this.parameters)};this.send=function(){this.locked||(this.modifyForPub(),
this.setRetryTime(),this.locked=!0);if(this.active){this.setRetry();this.registerCallback();this.setUrl();this.sentAt=+new Date;var b=this,c=a.Util.attachScript(this.url,Function.prototype.bind?this.cancel.bind(this):function(){b.cancel()});c.parentNode.removeChild(c);a.log("url called after",this.id,this.sentAt-this.requestedAt,this.numTries,this.url)}};this.processResponse=function(b){0===b.length||!1===!!b?(this.returnedAt=+new Date,this.renderedAt=+new Date,a.log("empty response/null response/undefined response",
this.id,this.returnedAt-this.returnedAt,b)):(this.noRetry(),this.receivedAt=+new Date,"function"==typeof a.Pub.modifyResponse&&(b=a.Pub.modifyResponse(this,b)),this.respond(b))};this.cancel=function(){this.active=!1;clearTimeout(this.timeoutRef);a.log("cancelled request",this.id);var b=a.Pub.prepareDefaultResponse(this);if(null!==this.parameters.count&&1!=this.parameters.count){for(var c=[],d=0,e=this.parameters.count;d<e;d++)c.push(b);this.respond(c)}else this.respond(b)};this.respond=function(b){this.returnedAt=
+new Date;a.log("closing request",this.id,this.returnedAt-this.receivedAt,b);this.callback(b);this.renderedAt=+new Date;a.log("callback finished",this.id,this.renderedAt-this.receivedAt,this.renderedAt-this.returnedAt)};this.update=function(b){a.log("updating request",this.id);"function"==typeof a.Pub.applyMapResponse?(a.Pub.applyMapResponse(this,b),this.inputs[a.MAP_KEY]=1,this.map=!1,this.noRetry(),this.send()):this.applyInputs(b);this.locked=!1;this.map&&this.inputs.hasOwnProperty(a.MAP_KEY)&&
(this.noRetry(),this.send())}}}();"function"===typeof define&&define.amd&&define("tagDeliveryContent",[],function(){return a});e[a.GLOBAL_NAME]=a;a.hasOwnProperty("Pub")&&"object"===typeof a.Pub&&a.Pub.hasOwnProperty("GLOBAL_NAME")&&a.GLOBAL_NAME!=a.Pub.GLOBAL_NAME&&(e[a.Pub.GLOBAL_NAME]=a);if(e.hasOwnProperty("TagDeliveryQueue"))for(var g=0;g<e.TagDeliveryQueue.length;g++)"Pub.ctr.renderShelf"==e.TagDeliveryQueue[g]&&e[a.GLOBAL_NAME].Pub.ctr.renderShelf();return a});
